</main>
<!-- Background images -->
<div class="blob-top"><?= ApplicationController::svg('blob') ?></div>
<div class="blob-middle"><?= ApplicationController::svg('blob') ?></div>
<div class="blob-bottom"><?= ApplicationController::svg('blob') ?></div>
<!-- Print -->
<div class="print">Print</div>
<!-- To top -->
<div class="invisible to-top">Naar boven</div>
<!-- Require JavaScript file -->
<?php require_once JS; ?>
</body>
</html>
