<header>
  <h1 class="nav-title center">Curriculum Vitae</h1>
  <nav class="menu">
    <div class="nav-list end-x">
      <a class="nav-item nav-link center" href="#personalia">Personalia</a>
      <a class="nav-item nav-link center" href="#opleidingen">Opleidingen</a>
      <a class="nav-item nav-link center" href="#werkervaring">Werkervaring</a>
      <a class="nav-item nav-link center" href="#projecten">Projecten</a>
    </div>
  </nav>
  <button class="hamburger hamburger--squeeze" type="button">
    <span class="hamburger-box center">
      <span class="hamburger-inner"></span>
    </span>
  </button>
</header>
