<!-- This website is made using the Simpl framework. You can read more about Simpl here: https://www.github.com/IJuanTM/Simpl/ -->
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Page title -->
  <title><?= PROJECT_NAME ?> - Iwan van der Wal</title>
  <!-- Require favicon, meta and CSS files -->
  <?php
  require_once FAVICON;
  require_once META;
  require_once CSS;
  ?>
</head>
<body>
<!-- No script -->
<noscript>To use this website to it's fullest potential, please enable JavaScript!</noscript>
<!-- Get header -->
<?php $this->part('header'); ?>
<!-- Content -->
<main class="content">
