<?php use app\Controllers\FormController; ?>

<section class="login">
  <div class="row center-x">
    <form class="col" method="POST" action="">
      <div class="row">
        <div class="col center-x">
          <h2>Admin Login</h2>
        </div>
      </div>

      <?= FormController::$alert ?>

      <div class="row">
        <div class="col form-group">
          <div class="row">
            <label class="col" for="email">Email: <span class="required">*</span></label>
          </div>
          <div class="row input-group <?= (isset($_POST['submit']) && empty($_POST['email'])) ? 'error' : '' ?>">
            <div class="col input-prepend center f-0"><i class="fas fa-at"></i></div>
            <input class="col" id="email" type="email" name="email" placeholder="Enter email:" value="<?= $_POST['email'] ?? '' ?>">
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col form-group">
          <div class="row">
            <label class="col" for="password">Password: <span class="required">*</span></label>
            <div class="col password-warning end-x hidden">Caps lock is on!</div>
          </div>
          <div class="row input-group <?= (isset($_POST['submit']) && empty($_POST['password'])) ? 'error' : '' ?>">
            <div class="col input-prepend center f-0"><i class="fas fa-key"></i></div>
            <input class="col input-password" id="password" type="password" name="password" placeholder="Enter password:">
            <div class="col input-append center f-0"><i class="fas fa-eye password-toggle"></i></div>
          </div>
          <div class="row">
            <div class="col">
              <p class="form-details">Forgot your password? <a href="<?= $this->url('forgot-password') ?>" aria-label="Link to forgot password page">Click here</a>.</p>
            </div>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col">
          <p class="form-details">Don't have an account? <a href="<?= $this->url('register') ?>" aria-label="Link to register page">Click here</a> to register.</p>
        </div>
      </div>

      <div class="row option-row center-x">
        <div class="col f-0">
          <p>Stay logged in?</p>
        </div>
        <div class="col center-y f-0">
          <label for="remember">
            <input class="remember-checkbox" id="remember" type="checkbox" name="remember">
          </label>
        </div>
      </div>

      <div class="row button-row center-x">
        <button class="col center-y f-0" type="submit" name="submit" aria-label="Button to submit the login form"><i class="fas fa-right-to-bracket"></i>Login</button>
      </div>
    </form>
  </div>
</section>
