<?php ?>

<section class="home">
  <div class="row profile-header center-x">
    <div class="col name f-0 center-x">
      <div class="row">
        <div class="col">
          <h1>Iwan van der Wal</h1>
        </div>
      </div>

      <div class="row">
        <div class="col">
          <p>Junior Software Engineer</p>
        </div>
      </div>
    </div>

    <div class="col image f-0">
      <img src="<?= $this->url('/img/svg/pf.svg') ?>" alt="Profiel foto van Iwan van der Wal">
    </div>
  </div>

  <div class="row reverse">
    <div class="col no-print">
      <div class="row">
        <div class="col">
          <h2>Wie ben ik</h2>
        </div>
      </div>

      <hr>

      <div class="row">
        <div class="col text">
          <p>Mijn naam is Iwan, ik ben <?= date_diff(date_create('20011025'), date_create(date('Ymd')))->format('%y') ?> jaar oud en woon in Utrecht.</p>

          <p>Al mijn hele leven heb ik een passie voor computers en technologie. Ik ben altijd bezig met het leren van nieuwe dingen en het uitproberen van nieuwe technologieën. Ik werk altijd zorgvuldig en nauwkeurig en ben altijd op zoek naar manieren om mezelf te verbeteren. Ik werk graag in een team, maar kan ook goed zelfstandig werken.</p>

          <p>Mijn kennis ligt vooral bij webdevelopment met PHP, HTML, CSS en JavaScript, maar ik ben ook bekend met C# (.NET), Java en Python. Ik werk graag aan zowel de front- als de back-end van een applicatie, en vind het leuk om te zien hoe de verschillende onderdelen samen komen. Verder heb ik ook ervaring met databases, zoals MySQL en SQLite, en met versiebeheer, zoals Git. Daarnaast kan ik goed overweg met Linux en Windows en ben ik bekend met het werken met de command line.</p>

          <p>Ik kom graag ik contact om verder te praten over mijn ervaringen en kennis, en eventueel over wat ik voor u kan betekenen.</p>
        </div>
      </div>
    </div>

    <div class="col" id="personalia">
      <div class="row">
        <div class="col">
          <h2>Personalia</h2>
        </div>
      </div>

      <hr>

      <div class="row">
        <div class="col double-column">
          <div class="row">
            <div class="col double-list">
              <div class="row">
                <div class="col label-md">Geboortedatum</div>
                <div class="col">25 oktober 2001</div>
              </div>

              <div class="row">
                <div class="col label-md">Nationaliteit</div>
                <div class="col">Nederlandse</div>
              </div>

              <div class="row">
                <div class="col label-md">Adres</div>
                <div class="col">
                  <div class="row">

                    <?php if (isset($_SESSION['user']) || isset($_SESSION['token'])) : ?>
                      <div class="col">Scheldestraat 49</div>
                    <?php else : ?>
                      <div class="col obfuscated-row"><span class="obfuscated" title="Content verborgen voor privacy, klik voor meer informatie.">Gkfeasdcvbret 23</span><i class="fas fa-eye-slash access-modal"></i></div>
                    <?php endif ?>

                  </div>
                  <div class="row">
                    <?php if (isset($_SESSION['user']) || isset($_SESSION['token'])) : ?>
                      <div class="col">3522 CB Utrecht</div>
                    <?php else : ?>
                      <div class="col obfuscated-row"><span class="obfuscated" title="Content verborgen voor privacy, klik voor meer informatie.">6578 KG</span><i class="fas fa-eye-slash access-modal"></i> Utrecht</div>
                    <?php endif ?>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col double-list">
              <div class="row">
                <div class="col label-md">E-mailadres</div>
                <div class="col"><a href="mailto:iwan2510@gmail.com">iwan2510@gmail.com</a></div>
              </div>

              <div class="row">
                <div class="col label-md">Telefoonnummer</div>
                <?php if (isset($_SESSION['user']) || isset($_SESSION['token'])) : ?>
                  <div class="col"><a href="tel:+31637276904">+31 6 37 27 69 04</a></div>
                <?php else : ?>
                  <div class="col obfuscated-row">+31 6 <span class="obfuscated" title="Content verborgen voor privacy, klik voor meer informatie.">78 12 23 90</span><i class="fas fa-eye-slash access-modal"></i></div>
                <?php endif ?>
              </div>

              <div class="row">
                <div class="col label-md">LinkedIn</div>
                <div class="col"><a href="https://www.linkedin.com/in/iwanvanderwal" target="_blank">iwanvanderwal</a></div>
              </div>

              <div class="row">
                <div class="col label-md">Website</div>
                <div class="col"><a href="https://www.iwanvanderwal.nl" target="_blank">iwanvanderwal.nl</a></div>
              </div>

              <div class="row">
                <div class="col label-md">GitHub</div>
                <div class="col"><a href="https://github.com/IJuanTM" target="_blank">IJuanTM</a></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col" id="opleidingen">
      <div class="row">
        <div class="col">
          <h2>Opleidingen</h2>
        </div>
      </div>

      <hr>

      <div class="row">
        <div class="col items">
          <div class="row item-head">
            <div class="col time">2020 - 2024</div>

            <div class="col">
              <div class="row">
                <div class="col">
                  <h3><span class="hl-red">HBO Bachelor</span> / <span class="hl-white">HBO-ICT</span> / <span class="hl-green">Software Engineering</span></h3>

                  <h3 class="hl-purple">De Haagse Hogeschool</h3>
                </div>
              </div>

              <div class="row">
                <div class="col">
                  <ul class="list">
                    <li>Specialisatie in Software Engineering</li>
                    <li>Minor Software Reversing and Exploitation gedaan</li>
                    <li>Favoriete vak: WPFW - Webprogramming, Frameworks & Usability, leren werken met C# en .NET en met accessibility</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>

          <div class="row item-head">
            <div class="col time">2019 - 2020</div>

            <div class="col">
              <div class="row">
                <div class="col">
                  <h3><span class="hl-red">MBO-4</span> / <span class="hl-white">Applicatie- en mediaontwikkelaar</span> / <span class="hl-green">Webdevelopment</span></h3>

                  <h3 class="hl-purple">MBO Utrecht</h3>
                </div>
              </div>

              <div class="row">
                <div class="col">
                  <ul class="list">
                    <li>Versneld afgerond in 1,5 jaar</li>
                    <li>Favoriete vak: Programming, leren werken met HTML, CSS en PHP</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>

          <div class="row item-head">
            <div class="col time">2013 - 2018</div>

            <div class="col">
              <div class="row">
                <div class="col">
                  <h3><span class="hl-red">HAVO</span> / <span class="hl-green">Natuur en Gezondheid</span></h3>

                  <h3 class="hl-purple">Leidsche Rijn College</h3>
                </div>
              </div>

              <div class="row">
                <div class="col">
                  <ul class="list">
                    <li>Informatica als keuzevak</li>
                    <li>Favoriete vakken: Informatica en Engels</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="col no-print">
      <div class="row">
        <div class="col">
          <h2>Certificaten</h2>
        </div>
      </div>

      <hr>

      <div class="row">
        <div class="col items">
          <div class="row item-head">
            <div class="col time">2024</div>

            <div class="col">
              <div class="row">
                <div class="col">
                  <h3 class="hl-purple">ADVUT - Unit Testing with C#</h3>

                  <h3><span class="hl-green">Info Support</span></h3>
                </div>
              </div>

              <div class="row">
                <div class="col">
                  <ul class="list">
                    <li>Behandelde onderwerpen: Unit testing, Test Driven Development, Mocking (Moq en FakeItEasy), Dependency Injection, Mutation testing, Test coverage en Test containers</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col" id="werkervaring">
      <div class="row">
        <div class="col">
          <h2>Werkervaring</h2>
        </div>
      </div>

      <hr>

      <div class="row">
        <div class="col items">
          <div class="row item-head">
            <div class="col time">2023 - heden</div>

            <div class="col">
              <div class="row">
                <div class="col">
                  <h3><span class="hl-red">Full-stack Developer</span> / <span class="hl-green">Ecoteers</span></h3>

                  <h3 class="hl-purple">Utrecht</h3>
                </div>
              </div>

              <div class="row">
                <div class="col">
                  <ul class="list">
                    <li>Verder ontwikkelen van het systeem uit de stage opdracht</li>
                    <li>Het beheren van het systeem en de database</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>

          <div class="row item-head">
            <div class="col time">2024</div>

            <div class="col">
              <div class="row">
                <div class="col">
                  <h3><span class="hl-red">Afstudeerder</span> / <span class="hl-green">Info Support</span></h3>

                  <h3 class="hl-purple">Veenendaal</h3>
                </div>
              </div>

              <div class="row">
                <div class="col">
                  <ul class="list">
                    <li>HBO afstudeeropdracht</li>
                    <li>Maken van een berichtenmonitor applicatie voor een klant van Info Support</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>

          <div class="row item-head">
            <div class="col time">2023</div>

            <div class="col">
              <div class="row">
                <div class="col">
                  <h3><span class="hl-red">Stagair</span> / <span class="hl-green">Ecoteers</span></h3>

                  <h3 class="hl-purple">Utrecht</h3>
                </div>
              </div>

              <div class="row">
                <div class="col">
                  <ul class="list">
                    <li>HBO 3e-jaars stage</li>
                    <li>Maken van een intern ticket/project management systeem</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>

          <div class="row item-head">
            <div class="col time">2020</div>

            <div class="col">
              <div class="row">
                <div class="col">
                  <h3><span class="hl-red">Stagair</span> / <span class="hl-green">Clearsite</span></h3>

                  <h3 class="hl-purple">Nieuwegein</h3>
                </div>
              </div>

              <div class="row">
                <div class="col">
                  <ul class="list">
                    <li>MBO afstudeerstage</li>
                    <li>Dashboard applicatie gemaakt voor het bedrijf</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="col no-print" id="vaardigheden">
      <div class="row">
        <div class="col">
          <h2>Vaardigheden</h2>
        </div>
      </div>

      <hr>

      <div class="row">
        <div class="col items">
          <div class="row item-head">
            <div class="col">
              <div class="row">
                <div class="col">
                  <h3><span class="hl-purple">Programeertalen</span></h3>
                </div>
              </div>

              <div class="row">
                <div class="col">
                  <ul class="list">
                    <li>PHP</li>
                    <li>HTML</li>
                    <li>CSS</li>
                    <li>JavaScript</li>
                    <li>C#</li>
                    <li>.NET</li>
                    <li>Java</li>
                    <li>Python</li>
                  </ul>
                </div>
              </div>
            </div>

            <div class="col">
              <div class="row">
                <div class="col">
                  <h3><span class="hl-green">Frameworks en tools</span></h3>
                </div>
              </div>

              <div class="row">
                <div class="col">
                  <ul class="list">
                    <li>Laravel</li>
                    <li>Blazor</li>
                    <li>Bootstrap</li>
                    <li>Sass</li>
                    <li>Git</li>
                    <li>Composer</li>
                    <li>NPM</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>

          <div class="row item-head">
            <div class="col">
              <div class="row">
                <div class="col">
                  <h3><span class="hl-red">Databases en infrastructuur</span></h3>
                </div>
              </div>

              <div class="row">
                <div class="col">
                  <ul class="list">
                    <li>MySQL</li>
                    <li>SQLite</li>
                    <li>Apache</li>
                    <li>Azure</li>
                    <li>Docker</li>
                  </ul>
                </div>
              </div>
            </div>

            <div class="col">
              <div class="row">
                <div class="col">
                  <h3><span class="hl-yellow">Overige technieken</span></h3>
                </div>
              </div>

              <div class="row">
                <div class="col">
                  <ul class="list">
                    <li>Linux CLI</li>
                    <li>Windows CLI</li>
                    <li>SCRUM</li>
                    <li>DevOps</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col no-print">
      <div class="row">
        <div class="col">
          <h2>Projecten</h2>
        </div>
      </div>

      <hr>

      <div class="row">
        <div class="col items">
          <div class="row item-head">
            <div class="col time">2024</div>

            <div class="col">
              <div class="row">
                <div class="col">
                  <h3><span class="hl-purple">Berichtenmonitor applicatie</span></h3>
                </div>
              </div>

              <div class="row">
                <div class="col">
                  <p class="text hl-white">Een applicatie voor het monitoren van berichten van een klant van Info Support. Gemaakt met behulp van C#, .NET, Blazor, HTML en CSS.</p>
                </div>
              </div>
            </div>
          </div>

          <div class="row item-head">
            <div class="col time">2023 - heden</div>

            <div class="col">
              <div class="row">
                <div class="col">
                  <h3><span class="hl-purple">Ecoteers Systeem</span></h3>
                </div>
              </div>

              <div class="row">
                <div class="col">
                  <p class="text hl-white">Een ticket/project management systeem voor het bedrijf Ecoteers. Gemaakt met behulp van Laravel, MySQL, HTML, CSS, JavaScript en Sass. Momenteel nog in ontwikkeling.</p>
                </div>
              </div>
            </div>
          </div>

          <div class="row item-head">
            <div class="col time">2022 - heden</div>

            <div class="col">
              <div class="row">
                <div class="col">
                  <h3><span class="hl-purple">Portfolio website</span> / <a href="https://www.iwanvanderwal.nl" target="_blank">Website</a></h3>
                </div>
              </div>

              <div class="row">
                <div class="col">
                  <p class="text hl-white">Mijn eigen portfolio-website voor het showcasen van mijn projecten en ervaringen. Gemaakt met behulp van PHP, HTML, CSS, JavaScript en Sass. Nog work-in-progress.</p>
                </div>
              </div>
            </div>
          </div>

          <div class="row item-head">
            <div class="col time">2020 - heden</div>

            <div class="col">
              <div class="row">
                <div class="col">
                  <h3><span class="hl-purple">Simpl</span> / <a href="https://simpl.iwanvanderwal.nl" target="_blank">Website</a> / <a href="https://github.com/IJuanTM/simpl" target="_blank">GitHub</a></h3>
                </div>
              </div>

              <div class="row">
                <div class="col">
                  <p class="text hl-white">Een PHP, HTML, CSS, JavaScript en Sass framework. Begonnen als een handige template om snel te beginnen aan een nieuwe website, daarna verder uitgebreid met meer functies. Nog steeds bezig met aanvullen en verbeteren.</p>
                </div>
              </div>
            </div>
          </div>

          <div class="row item-head">
            <div class="col time">2022</div>

            <div class="col">
              <div class="row">
                <div class="col">
                  <h3><span class="hl-purple">ZMDH zorgkliniek website</span> / <a href="https://github.com/aycan-acn/Care-Clinic-ZMDH" target="_blank">GitHub</a></h3>
                </div>
              </div>

              <div class="row">
                <div class="col">
                  <p class="text hl-white">Een website voor een zorgkliniek met een live chatsysteem. Gemaakt met C#, met behulp van .NET en SignalR. Gemaakt voor een project op mijn opleiding, afgerond met een <span class="hl-red">9,2</span>.</p>
                </div>
              </div>
            </div>
          </div>

          <div class="row item-head">
            <div class="col time">2021</div>

            <div class="col">
              <div class="row">
                <div class="col">
                  <h3><span class="hl-purple">ETWS dashboard website</span></h3>
                </div>
              </div>

              <div class="row">
                <div class="col">
                  <p class="text hl-white">Een dashboard voor het bekijken van opgewekte energie door een slim grijs-water opwek systeem. Gemaakt voor een project op mijn opleiding, samen met een API en database, afgrond met een <span class="hl-red">7,8</span>.</p>
                </div>
              </div>
            </div>
          </div>

          <div class="row item-head">
            <div class="col time">2020</div>

            <div class="col">
              <div class="row">
                <div class="col">
                  <h3><span class="hl-purple">Clearsite dashboard</span></h3>
                </div>
              </div>

              <div class="row">
                <div class="col">
                  <p class="text hl-white">Een dashboard voor stagebedrijf Clearsite, bedoeld om lopende projecten en de status van verschillende websites en servers te laten zien. Gemaakt om weer te geven op een groot scherm in de wachtruimte van het kantoor.</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
