<header>
  <div class="row navbar f-nowrap">
    <div class="col nav-title center f-0">
      <h6><?= ucwords(APP_NAME) ?></h6>
    </div>

    <nav class="col menu end-x">
      <div class="row nav-list w-auto f-0">
        <a class="col nav-item center f-0" href="<?= $this->url('home#personalia') ?>" aria-label="Link naar personalia sectie">Personalia</a>
        <a class="col nav-item center f-0" href="<?= $this->url('home#opleidingen') ?>" aria-label="Link naar opleidingen sectie">Opleidingen</a>
        <a class="col nav-item center f-0" href="<?= $this->url('home#werkervaring') ?>" aria-label="Link naar werkervaring sectie">Werkervaring</a>
        <a class="col nav-item center f-0" href="<?= $this->url('home#vaardigheden') ?>" aria-label="Link naar vaardigheden sectie">Vaardigheden</a>
        <?php if (isset($_SESSION['user']['id'])) : ?>
          <?php if ($_SESSION['user']['role'] == 1) : ?>
            <a class="col nav-item nav-link access-tokens center f-0" href="<?= $this->url('access-tokens') ?>" aria-label="Link naar access tokens overzicht">Access Tokens</a>
          <?php endif ?>
          <a class="col nav-item nav-link logout center f-0" href="<?= $this->url('logout') ?>" aria-label="Logout button"><i class="fas fa-right-from-bracket"></i> Logout</a>
        <?php endif ?>
      </div>
    </nav>

    <div class="col nav-options">
      <div class="row end-x h-100">
        <button class="col hamburger hamburger--squeeze f-0" type="button" aria-label="Open navigatie menu" aria-controls="navigation" aria-expanded="false" tabindex="1">
          <span class="hamburger-box center">
            <span class="hamburger-inner"></span>
          </span>
        </button>
      </div>
    </div>
  </div>
</header>
