<!-- Reset (load first) -->
<link rel="stylesheet" href="<?= $this->url('css/reset.css') ?>">

<!-- Fonts -->
<link rel="stylesheet" href="<?= $this->url('fonts/fonts.css') ?>">

<!-- Font Awesome Icons -->
<link rel="stylesheet" href="<?= $this->url('fonts/icons/brands.min.css') ?>">
<link rel="stylesheet" href="<?= $this->url('fonts/icons/fontawesome.min.css') ?>">
<link rel="stylesheet" href="<?= $this->url('fonts/icons/regular.min.css') ?>">
<link rel="stylesheet" href="<?= $this->url('fonts/icons/solid.min.css') ?>">

<!-- Hamburgers -->
<link rel="stylesheet" href="<?= $this->url('css/hamburgers.min.css') ?>">

<!-- Main (load last) -->
<link rel="stylesheet" href="<?= $this->url('css/main.min.css') ?>">
