<!-- Charset -->
<meta charset="UTF-8">

<!-- Viewport -->
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- Copyright and author -->
<meta name="copyright" content="&copy; Iwan van der Wal">
<meta name="author" content="Iwan van der Wal" lang="en">

<!-- Description and keywords -->
<meta name="description" content="Mijn curriculum vitae website!">
<meta name="keywords" content="cv, curriculum vitae">

<!-- Theme color -->
<meta name="theme-color" content="#09203F">
